service: glide-authenticate
provider:
  name: aws
  runtime: nodejs8.10
package:
  include:
    - dist/**
functions:
  callback:
    handler: dist/events/oauth/callback.default
    events:
      - http:
          path: oauth/callback
          method: get
  connect:
    handler: dist/events/connect.default
    events:
      - websocket:
          route: $connect
  message:
    handler: dist/events/message.default
    events:
      - websocket:
          route: $default
  refresh:
    handler: dist/events/oauth/refresh.default
    events:
      - http:
          path: oauth/refresh
          method: post
